name: Integration tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
      - run: ./scripts/build-java-engine
      - run: npm run integration-test
        working-directory: backend/
