name: Build and publish tank game docker image

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "tankgameorg/ui"

jobs:
  testing:
    name: Tests
    uses: TankGameOrg/ui/.github/workflows/testing.yml@ci-improvements

  build-and-push-image:
    needs:
      - testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Set up QEMU mutli arch
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Log in to the Container registry
      #   uses: docker/login-action@v3
      #   if: github.event_name != 'pull_request'
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     build-args: 'BUILD_INFO=${{ github.ref_name }} @ ${{ github.sha }} #${{ github.run_number }}'
      #     platforms: linux/amd64,linux/arm64
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      #     labels: ${{ steps.meta.outputs.labels }}
