name: Build and publish docker image

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "tankgameorg/ui"

jobs:
  testing:
    name: Tests
    uses: TankGameOrg/ui/.github/workflows/testing.yml@main

  build-and-push-image:
    needs:
      - testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: ./scripts/build release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
