name: Unit tests

on:
  push:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: backend/
      - run: npm test
        working-directory: backend/

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Checkout java engine
        run: ./scripts/build-java-engine checkout
      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
          distribution: 'temurin'
      - name: Build java engine
        run: ./scripts/build-java-engine build engine
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend/
      - name: Run integration tests
        run: npm run integration-test
        working-directory: backend/
